{
  "language": "node_js",
  "node_js": 8.5.0,

  "env": "CXX=g++-4.8",

  "addons": {
    "apt": {
      "sources": ubuntu-toolchain-r-test,
      "packages": g++-4.8
    }
  },

  "install": [
    "npm install typescript -g",
    "npm install mocha -g",
    "npm install ts-mocha -g",
    "npm install amd-loader -g",
    "npm install typedoc -g",
    "npm install jquery -g",
    "npm install --save-dev @types/jquery",
    "npm install jsdom",
    "npm install jsdom-global",
    "npm install canvas"
  ],

  "script": [
    "make all",
    "make test"
  ],

  "group": "stable",
  "dist": "precise",
  "os": "linux",

  "notifications": {
    "email": false
  },

  "deploy": {
      "provider": "pages",
      "skip_cleanup": true,
      "local_dir": "build",
      "github_token": $GITHUB_TOKEN,
      "on": {
        "branch": master
        }
    }
}
