{
  "language": "node_js",
  "node_js": 8.5.0,

  "env": "CXX=g++-4.8",

  "addons": {
    "apt": {
      "sources": ubuntu-toolchain-r-test,
      "packages": ["g++-4.8", "libgif-dev"]
    }
  },

  "install": [],

  "script": [
    "make setup",
    "make all",
    "mv docs build"
  ],

  "group": "stable",
  "dist": "precise",
  "os": "linux",

  "notifications": {
    "email": false
  },

  "deploy": {
      "provider": "pages",
      "skip_cleanup": true,
      "local_dir": "build",
      "github_token": $GITHUB_TOKEN,
      "on": {
        "branch": master
        }
    }
}
