{
  "language": "node_js",
  "node_js": 8.5.0,

  "install": [
    "npm install typescript -g",
    "npm install mocha -g",
    "npm install ts-mocha -g",
    "npm install amd-loader -g",
    "npm install typedoc -g"
  ],

  "script": [
    "make all",
    "make test"
  ],

  "group": "stable",
  "dist": "precise",
  "os": "linux",

  notifications: {
    email: false
  }
}
